version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: pizza_postgres
    environment:
      POSTGRES_DB: pizza_market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3296
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizza_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pizza_market_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3296
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres-data: