CREATE SEQUENCE IF NOT EXISTS ingredients_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS order_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS orders_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pizza_images_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pizza_pizza_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pizza_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS promo_codes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE order_items
(
    item_price     numeric(10, 2)                          NOT NULL,
    quantity       INTEGER                                 NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT,
    pizza_id       BIGINT,
    pizza_pizza_id BIGINT,
    price          numeric(38, 2),
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
    total_price      numeric(38, 2)                          NOT NULL,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_time       TIMESTAMP WITHOUT TIME ZONE,
    customer_name    VARCHAR(255),
    delivery_address VARCHAR(255),
    phone_number     VARCHAR(255),
    promo_code_id    BIGINT,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE pizza
(
    is_available      BOOLEAN,
    price             numeric(38, 2),
    pizza_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pizza_description VARCHAR(1000),
    pizza_name        VARCHAR(255),
    CONSTRAINT pizza_pkey PRIMARY KEY (pizza_id)
);

CREATE TABLE pizza_images
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pizza_id           BIGINT,
    size               BIGINT,
    content_type       VARCHAR(255),
    name               VARCHAR(255),
    original_file_name VARCHAR(255),
    bytes              OID,
    CONSTRAINT pizza_images_pkey PRIMARY KEY (id)
);

CREATE TABLE promo_codes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    code           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    discount_type  VARCHAR(255),
    discount_value numeric(38, 2),
    valid_from     TIMESTAMP WITHOUT TIME ZONE,
    valid_to       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT promo_codes_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255),
    role         VARCHAR(255)                            NOT NULL,
    enabled      BOOLEAN,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE promo_codes
    ADD CONSTRAINT ukj9mo0xgfs34t6e3c17anidd83 UNIQUE (code);

ALTER TABLE order_items
    ADD CONSTRAINT fk25049v8jdsga78lc9epetwpld FOREIGN KEY (pizza_id) REFERENCES pizza (pizza_id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fk9tcfk67gy42mwdo87o9bwvp2a FOREIGN KEY (pizza_pizza_id) REFERENCES pizza (pizza_id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE NO ACTION;

ALTER TABLE pizza_images
    ADD CONSTRAINT fkso99gv2jw7152jc6768ialm00 FOREIGN KEY (pizza_id) REFERENCES pizza (pizza_id) ON DELETE NO ACTION;

ALTER TABLE orders
    ADD CONSTRAINT fkwlo1wcmsoggpqbgv2kp1ndx7 FOREIGN KEY (promo_code_id) REFERENCES promo_codes (id) ON DELETE NO ACTION;